DROP TABLE book;
DROP TABLE  person;

CREATE TABLE person(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) not null,
    year_of_birth integer not null
);
CREATE TABLE book(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) not null,
    author varchar(100) not null,
    year integer not null,
    person_id integer REFERENCES person ON DELETE SET NULL
);

ALTER TABLE book ADD COLUMN date timestamp;
UPDATE book SET date = '2023-01-01' WHERE id = 1;
UPDATE book SET person_id = 3 WHERE id = 1;
