CREATE TABLE person(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) not null,
    year_of_birth integer not null
);
CREATE TABLE book(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) not null,
    author varchar(100) not null,
    year integer not null,
    person_id integer REFERENCES person ON DELETE SET NULL
);